version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: hmi_postgres
    restart: always
    environment:
      POSTGRES_USER: hmiuser
      POSTGRES_PASSWORD: hmipassword
      POSTGRES_DB: hmidb
    ports:
      - "5432:5432"   # 로컬 5432 포트를 컨테이너 5432에 매핑
    volumes:
      - pgdata:/var/lib/postgresql/data  # 데이터 영속화

volumes:
  pgdata:
